/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import Persistencia.AlumnoData;
import Modelo.Alumno;
import Persistencia.Conexion;
import java.awt.Graphics;
import java.awt.Image;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JDesktopPane;

/**
 *
 * @author Juan
 */
public class jfPrincipal extends javax.swing.JFrame {
    public static ArrayList<Alumno> listaAlumnos = new ArrayList<>();
    
    
    
    
    public jfPrincipal() {
        initComponents();
        
        jdpEscritorio = new DesktopConFondo("/img/ULP_Logo.jpeg");
        setContentPane(jdpEscritorio);
        Conexion conexion = new Conexion(
                "jdbc:mariadb://localhost:3306/universidadulp","root",""
        );
        AlumnoData ad = new AlumnoData(conexion);
        
        ArrayList<Alumno> aux = ad.obtenerAlumnos();
        for (int i=0; i<aux.size();i++){
            System.out.println(aux.get(i));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdpEscritorio = new javax.swing.JDesktopPane();
        jmbBarraMenu = new javax.swing.JMenuBar();
        jmAlumnos = new javax.swing.JMenu();
        jmiGestionAlumnos = new javax.swing.JMenuItem();
        jmMaterias = new javax.swing.JMenu();
        jmiGestionMaterias = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        javax.swing.GroupLayout jdpEscritorioLayout = new javax.swing.GroupLayout(jdpEscritorio);
        jdpEscritorio.setLayout(jdpEscritorioLayout);
        jdpEscritorioLayout.setHorizontalGroup(
            jdpEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );
        jdpEscritorioLayout.setVerticalGroup(
            jdpEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 697, Short.MAX_VALUE)
        );

        jmAlumnos.setText("Alumnos");

        jmiGestionAlumnos.setText("Gestion de Alumnos");
        jmiGestionAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiGestionAlumnosActionPerformed(evt);
            }
        });
        jmAlumnos.add(jmiGestionAlumnos);

        jmbBarraMenu.add(jmAlumnos);

        jmMaterias.setText("Materias");

        jmiGestionMaterias.setText("Gestion de Materias");
        jmiGestionMaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiGestionMateriasActionPerformed(evt);
            }
        });
        jmMaterias.add(jmiGestionMaterias);

        jmbBarraMenu.add(jmMaterias);

        setJMenuBar(jmbBarraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpEscritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpEscritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiGestionAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiGestionAlumnosActionPerformed
        jdpEscritorio.removeAll();
        jdpEscritorio.repaint();
        jifVistaAlumnos va = new jifVistaAlumnos();
        va.setVisible(true);
        jdpEscritorio.add(va);
        va.toFront();
    }//GEN-LAST:event_jmiGestionAlumnosActionPerformed

    private void jmiGestionMateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiGestionMateriasActionPerformed
        jdpEscritorio.removeAll();
        jdpEscritorio.repaint();
        jifVistaMaterias m = new jifVistaMaterias();
        m.setVisible(true);
        jdpEscritorio.add(m);
        m.toFront();
    }//GEN-LAST:event_jmiGestionMateriasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfPrincipal().setVisible(true);
            }
        });
        
        
        System.out.println(listaAlumnos.toString());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jdpEscritorio;
    private javax.swing.JMenu jmAlumnos;
    private javax.swing.JMenu jmMaterias;
    private javax.swing.JMenuBar jmbBarraMenu;
    private javax.swing.JMenuItem jmiGestionAlumnos;
    private javax.swing.JMenuItem jmiGestionMaterias;
    // End of variables declaration//GEN-END:variables
class DesktopConFondo extends JDesktopPane {
        private Image imagen;
        public DesktopConFondo(String rutaImagen) {
            java.net.URL imgURL = getClass().getResource(rutaImagen);
        if (imgURL != null) {
            this.imagen = new ImageIcon(imgURL).getImage();
        } else {
            System.err.println("No se encontró la imagen: " + rutaImagen);
            }
        }
        
        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
            if (imagen != null) {
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            }
        }
    }
}
