/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;

import Modelo.Alumno;
import Modelo.Inscripcion;
import Modelo.Materia;
import Persistencia.AlumnoData;
import Persistencia.InscripcionData;
import Persistencia.Conexion;
import java.util.List;
import javax.swing.table.DefaultTableModel;

public class jifVistaListarInscripciones extends javax.swing.JInternalFrame {

    private Conexion conexion;
    private AlumnoData alumnoData;
    private InscripcionData inscripcionData;
    private DefaultTableModel modeloTabla;
    
    public jifVistaListarInscripciones() {
        initComponents();
        conexion = new Conexion("jdbc:mariadb://localhost:3306/universidad", "root", "");
        alumnoData = new AlumnoData(conexion);
        inscripcionData = new InscripcionData(conexion);
        
        modeloTabla = new DefaultTableModel();
        armarCabecera();
        cargarComboAlumnos();
        
        comboAlumno.addActionListener(e -> cargarTabla());
    }
    
    private void armarCabecera(){
        modeloTabla.addColumn("Materia");
        modeloTabla.addColumn("Ciclo Lectivo");
        modeloTabla.addColumn("Nota");
        tablaInscripciones.setModel(modeloTabla);
    }
    
    private void cargarComboAlumnos(){
        comboAlumno.removeAllItems();
        comboAlumno.addItem("Seleccione un alumno");
        for (Alumno a : alumnoData.obtenerAlumnos()){
            if (a.isEstado()){
                comboAlumno.addItem(a.getId_alumno() + " - " + a.getApellido() + ", " + a.getNombre());
            }
        }
    }
    
    private void cargarTabla(){
        modeloTabla.setRowCount(0);
        int index = comboAlumno.getSelectedIndex();
        if (index <= 0) return;
        
        String seleccionado = (String) comboAlumno.getSelectedItem();
        int idAlumno = Integer.parseInt(seleccionado.split(" - ") [0]);
        
        List<Inscripcion> inscripciones = inscripcionData.obtenerInscripcionesPorAlumno(idAlumno);
        
        for (Inscripcion ins : inscripciones){
            Materia m = ins.getIdMateria();
            modeloTabla.addRow(new Object[]{
            m.getNombre(),
            m.getAnio(),
            ins.getNota()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        comboAlumno = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaInscripciones = new javax.swing.JTable();

        setClosable(true);

        jLabel1.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        jLabel1.setText("Listar Inscripciones");

        comboAlumno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---- Seleccione un Alumno ----" }));

        tablaInscripciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaInscripciones);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(comboAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(comboAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboAlumno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaInscripciones;
    // End of variables declaration//GEN-END:variables
}
